schema_version = "1.0.0"
id = "developer_utilities"
name = "Developer Utilities"
version = "1.1.3"
tagline = "Make life of addon developers easier"
maintainer = "scorpion81"
type = "add-on"
tags = ["Development"]
blender_version_min = "4.3.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/scorpion81/developer_utilities"
copyright = ["2024 scorpion81"]

[permissions]
files = "Open source files of addons for editing"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
  "*.png",
  "*.md",
  "testmod/*",
  "make.py",
]
